trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'Stampede - UI - BUILD'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'AZ_ADO_DEPLOYMENT'
  region: 'Central US'
  resourceGroupName: 'stampede-ci'
stages:

 - stage: CI
   displayName: CI Stage 
   variables:
     appName: 'stampede-ui-ci'
     storageAccountName: 'azfstuici'
     resourceGroupName: 'stampede-ci'  
     linuxFxVersion: 'DOCKER|rutzscocr.azurecr.io/stampedeui'  
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
            - task: HelmInstaller@0
              displayName: 'Install Helm 3.5.4'
              inputs:
                helmVersion: 3.5.4
                checkLatestHelmVersion: false
            - task: HelmDeploy@0
              displayName: 'helm upgrade'
              inputs:
                azureSubscription: 'Demo Account'
                azureResourceGroup: 'rutzsco-aks'
                kubernetesCluster: 'rutzsco-aks1'
                command: upgrade
                chartType: FilePath
                chartPath: '$(System.DefaultWorkingDirectory)/_BUILD/Helm/api-$(Build.BuildNumber).tgz'
                chartVersion: '$(Build.BuildNumber)'
                releaseName: api
                overrideValues: 'image.tag=$(Build.BuildNumber)'
                resetValues: true