trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-aks-app - BUILD'
  
variables:
  vmImageName: 'ubuntu-18.04'
  azureSubscription: 'Demo Account'

stages:

 - stage: CI
   displayName: CI Stage 
   variables:
     kubernetesCluster: 'rutzsco-aks1'
     resourceGroupName: 'rutzsco-aks'  
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
            - task: PowerShell@2
              inputs:
                targetType: 'filePath'
                filePath: $(Pipeline.Workspace)/build/Deploy/test.ps1
                failOnStderr: true
                showWarnings: true
              displayName: 'Testing'
            - task: PowerShell@2
              inputs:
                targetType: 'filePath'
                filePath: $(Pipeline.Workspace)/build/Deploy/GetServiceStatus.ps1
                failOnStderr: true
                showWarnings: true
              displayName: 'Get Status'
           
            