parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: clusterName
  default: ''
- name: dnsPrefix
  default: ''
- name: logAnalyticsWorkspace
  default: ''
- name: sshRSAPublicKey
  default: ''
- name: acrResourceGroup
  default: ''
- name: acrName
  default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureResourceGroupDeployment@2
              displayName: '1. Create Log Analytics Workspace'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/log-analytics.json'
                overrideParameters: '-name ${{ parameters.logAnalyticsWorkspace }}'
                deploymentOutputs: ResourceGroupDeploymentOutputs
            - task: AzureResourceGroupDeployment@2
              displayName: '2. Create AKS Infrastructure'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/aks-basic.json'
                overrideParameters: '-clusterName ${{ parameters.clusterName }} -dnsPrefix ${{ parameters.dnsPrefix }} -sshRSAPublicKey "${{ parameters.sshRSAPublicKey }}" -acrResourceGroupName ${{ parameters.acrResourceGroup }} -acrName ${{ parameters.acrName }}'
                deploymentOutputs: ResourceGroupDeploymentOutputs
            - task: AzureCLI@2
              displayName: 3. Create Ingress Namespace
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az aks get-credentials -n ${{ parameters.clusterName }} -g ${{ parameters.resourceGroupName }}
                  az acr helm install-cli
                  helm repo update
                  helm install frontend ingress-nginx/ingress-nginx \
                  --namespace ingress-controller \
                  --set controller.replicaCount=2 \
                  --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
                  --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux \
                  --set controller.admissionWebhooks.patch.nodeSelector."beta\.kubernetes\.io/os"=linux
            - task: AzureCLI@2
              enabled: false
              displayName: 3. Create Ingress Namespace
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az aks get-credentials -n ${{ parameters.clusterName }} -g ${{ parameters.resourceGroupName }}
                  kubectl create namespace ingress-controller