trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-aks-core - BUILD'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'
  resourceGroupName: 'rutzsco-demo-aks-private-eastus'
  location: 'eastus'
  templateFile: 'Infrastructure/private-aks-cluster/main.bicep'
  aksClusterName: 'rutzsco-demo-aks-private'
  virtualNetworkName: 'rutzsco-demo-aks-eastus-vnet'
  virtualNetworkNameRG: 'rutzsco-demo-aks-eastus-vnet'
  aksClusterKubernetesVersion: '1.23.5'
  aksClusterAdminUsername: 'developer'
  aksClusterSshPublicKey: '1.23.5'
  logAnalyticsWorkspaceName: 'rutzsco-demo-aks-private'
  vmAdminPasswordOrKey: '1.23.5'
  vmAdminUsername: 'developer'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      ls
      az group create --name $(resourceGroupName) --location $(location)  
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters location=$(location) aksClusterName=$(aksClusterName) aksClusterKubernetesVersion=$(aksClusterKubernetesVersion) aksClusterAdminUsername=$(aksClusterAdminUsername) aksClusterSshPublicKey=$(aksClusterSshPublicKey) logAnalyticsWorkspaceName=$(logAnalyticsWorkspaceName) virtualNetworkNameRG=$(virtualNetworkNameRG) virtualNetworkName=$(virtualNetworkName) 