trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-aks-core - BUILD'
  
variables:
  azureSubscription: 'Demo Account'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'CI-AKS'
    azureSubscription: ${{ variables.azureSubscription }}
    resourceGroupName: 'rutzsco-aks'
    region: 'East US'
    clusterName: 'rutzsco-aks1'
    dnsPrefix: 'rutzsco-aks1'
    logAnalyticsWorkspace: 'rutzsco-aks-logs'
    acrResourceGroup: 'rutzsco-core-cicd'
    acrName: 'rutzscocr'
    sshRSAPublicKey: $(sshRSAPublicKey)