trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-aks-core - BUILD'
  
variables:
  azureSubscription: 'Demo Account'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'CI-AKS'
    azureServiceConnection: $(azureSubscription)
    resourceGroupName: 'rutzsco-aks-002'
    clusterName: 'rutzsco-aks-002'
    location: 'eastus'
