parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureServiceConnection
  default: ''
- name: location
  default: ''
- name: resourceGroupName
  default: ''
- name: clusterName
  default: ''


stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }} 
                  az deployment group create -g ${{ parameters.resourceGroupName }}  --template-uri https://github.com/Azure/AKS-Construction/releases/download/0.8.9/main.json --parameters resourceName=${{ parameters.clusterName }} podCidr='10.240.100.0/23'  agentCount=1 agentVMSize=Standard_B2s agentCountMax=2 networkPlugin=kubenet osDiskType=Managed daprAddon=true